spring:
  application:
    name: auth-groupware

  datasource:
    url: jdbc:postgresql://localhost:5432/groupware_db
    username: myuser
    password: ENC(bg3SOL/khQb3hTHXdQ6a7Cc34D7c7SFq2DeqkSxg/ct7VZU9LCNmMmpCdmtAwZ6Z)
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # dev 환경이면 update / 운영이면 validate 추천
    show-sql: true
    properties:
      hibernate:
        default_schema: groupware
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # 1) Spring Security OAuth2 Client / Resource Server 설정
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: spring-groupware-app
            client-secret: ENC(mAGIvRdMo+gBrnq2l8l8/eJJ17OcB1VGSyA8JXs9+5lIXPFKQj8CTPtouVvmrjhUtwjOQPhtWqPgL02KERBAcspNhjyVLf/5HJ10+Nkp8iE=)
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
            provider: keycloak

        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/groupware
      #          jwk-set-uri: http://localhost:8080/realms/groupware/protocol/openid-connect/certs
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/groupware

# 2) Keycloak Admin API 사용을 위한 설정
keycloak:
  auth-server-url: http://localhost:8080
  realm: groupware
  client-id: spring-groupware-app
  client-secret: ENC(mAGIvRdMo+gBrnq2l8l8/eJJ17OcB1VGSyA8JXs9+5lIXPFKQj8CTPtouVvmrjhUtwjOQPhtWqPgL02KERBAcspNhjyVLf/5HJ10+Nkp8iE=)


logging:
  level:
    root: INFO                              # 전체 로그 기본 레벨
    org.springframework.security: DEBUG     # 스프링 시큐리티 디버그
    sun.rmi.transport.tcp: WARN             # RMI/JMX 잡음 억제

server:
  port: 8081